from __future__ import annotations

from .models import DagEdge, DagNode, Scenario, StateVar, StateVarKind
from .models import Condition, Effect


_dayu = Scenario(
    scenario_id="xia-dayu-zhishui",
    title="大禹治水",
    period="夏 · 约公元前 2070 年",
    summary="禹承父业，需在「堵」与「疏」之间抉择，平衡民心与水患，最终划定九州。",
    state_vars=[
        StateVar(key="strategy", label="治水策略", kind=StateVarKind.SCALE, bits=2, initial=0,
                 description="0=未定 1=承父之堵 2=改弦疏导 3=堵疏并举"),
        StateVar(key="morale", label="民心", kind=StateVarKind.SCALE, bits=3, initial=4,
                 description="0~7，初始 4"),
        StateVar(key="flood", label="河患", kind=StateVarKind.SCALE, bits=3, initial=6,
                 description="0~7，初始 6"),
        StateVar(key="nine_zhou", label="九州划定", kind=StateVarKind.BOOL, bits=1, initial=0),
    ],
    start_node="n_call",
    nodes=[
        DagNode(node_id="n_call", title="受命继业",
                narrative="父鲧治水九年不成，被殛于羽山。舜命你承继治水大任，朝野观望。"),
        DagNode(node_id="n_inherit", title="承父之堵",
                narrative="你沿用父法，筑堤围堵。短期见效，但水势愈积愈高，民众疲于劳役。"),
        DagNode(node_id="n_reform", title="改弦疏导",
                narrative="你召集水工，主张顺水之性，开渠引流。族老质疑，你需以身作则。"),
        DagNode(node_id="n_combine", title="堵疏并举",
                narrative="你折中两策，重要城邑筑堤，下游开渠分洪。工程浩大，需多调民力。"),
        DagNode(node_id="n_collapse", title="溃堤之变",
                narrative="积水冲垮堤防，下游良田尽没，民心大丧。",
                is_terminal=True),
        DagNode(node_id="n_field_survey", title="行九州之野",
                narrative="你亲历山川，三过家门而不入，划定九州，定贡赋。民众感佩。"),
        DagNode(node_id="n_pacify", title="水患渐平",
                narrative="十三载寒暑，疏通九河，水患渐平。诸侯朝觐。"),
        DagNode(node_id="n_dynasty", title="开夏之基",
                narrative="禅让的传统在你这里停歇——子启继位。中国第一个王朝由此开启。",
                is_terminal=True),
    ],
    edges=[
        DagEdge(edge_id="e_call_inherit", from_node="n_call", to_node="n_inherit",
                label="沿用父法 · 筑堤围堵",
                effects=[Effect(var="strategy", op="set", value=1),
                         Effect(var="morale", op="dec", value=1)],
                fallback_narrative="你选择延续父亲的方法。"),
        DagEdge(edge_id="e_call_reform", from_node="n_call", to_node="n_reform",
                label="改弦更张 · 顺水疏导",
                effects=[Effect(var="strategy", op="set", value=2)],
                fallback_narrative="你决心另辟新路。"),
        DagEdge(edge_id="e_call_combine", from_node="n_call", to_node="n_combine",
                label="折中之策 · 堵疏并举",
                effects=[Effect(var="strategy", op="set", value=3),
                         Effect(var="morale", op="dec", value=2)],
                fallback_narrative="你采纳折中之议。"),

        DagEdge(edge_id="e_inherit_collapse", from_node="n_inherit", to_node="n_collapse",
                label="苦撑数年 · 终至溃堤",
                conditions=[Condition(var="flood", op="ge", value=5)],
                effects=[Effect(var="flood", op="set", value=7),
                         Effect(var="morale", op="set", value=0)],
                fallback_narrative="水患积重难返。"),

        DagEdge(edge_id="e_reform_survey", from_node="n_reform", to_node="n_field_survey",
                label="率众踏勘 · 三过家门",
                effects=[Effect(var="flood", op="dec", value=3),
                         Effect(var="morale", op="inc", value=2)],
                fallback_narrative="你以身作则，踏遍九州。"),

        DagEdge(edge_id="e_combine_survey", from_node="n_combine", to_node="n_field_survey",
                label="督工巡野 · 安抚民众",
                conditions=[Condition(var="morale", op="ge", value=2)],
                effects=[Effect(var="flood", op="dec", value=2),
                         Effect(var="morale", op="inc", value=1)],
                fallback_narrative="你两手抓，民心渐复。"),
        DagEdge(edge_id="e_combine_collapse", from_node="n_combine", to_node="n_collapse",
                label="民力枯竭 · 工程崩坏",
                conditions=[Condition(var="morale", op="lt", value=2)],
                effects=[Effect(var="flood", op="set", value=7),
                         Effect(var="morale", op="set", value=0)],
                fallback_narrative="民心既失，工程难以维系。"),

        DagEdge(edge_id="e_survey_pacify", from_node="n_field_survey", to_node="n_pacify",
                label="划定九州 · 定贡赋",
                effects=[Effect(var="nine_zhou", op="set", value=1),
                         Effect(var="morale", op="inc", value=2),
                         Effect(var="flood", op="dec", value=2)],
                fallback_narrative="九州既定，水患渐平。"),

        DagEdge(edge_id="e_pacify_dynasty", from_node="n_pacify", to_node="n_dynasty",
                label="禅让停歇 · 子启继位",
                conditions=[Condition(var="nine_zhou", op="eq", value=1),
                            Condition(var="morale", op="ge", value=5)],
                effects=[],
                fallback_narrative="时移势易，王朝由此开启。"),
    ],
)


_REGISTRY: dict[str, Scenario] = {_dayu.scenario_id: _dayu}


_shang_yang = Scenario(
    scenario_id="qin-shang-yang-bianfa",
    title="商鞅变法",
    period="战国 · 秦孝公时期 · 公元前 359 ~ 前 338 年",
    summary="卫鞅入秦，受孝公倚重，推行徙木立信、奖励耕战、废井田、行县制。变法雷厉，旧贵咬牙，太子犯禁，新法去留与卫鞅命途皆悬于一刻。",
    state_vars=[
        StateVar(key="trust", label="孝公信任", kind=StateVarKind.SCALE, bits=3, initial=4,
                 description="0~7，初始 4"),
        StateVar(key="opposition", label="旧贵反对", kind=StateVarKind.SCALE, bits=3, initial=3,
                 description="0~7，初始 3"),
        StateVar(key="strength", label="国力", kind=StateVarKind.SCALE, bits=3, initial=3,
                 description="0~7，初始 3"),
        StateVar(key="law_kept", label="新法存续", kind=StateVarKind.BOOL, bits=1, initial=0),
    ],
    start_node="n_in_qin",
    nodes=[
        DagNode(node_id="n_in_qin", title="入秦献策",
                narrative="你由魏入秦，三见孝公始陈强国之术。孝公拍案称善，朝中却议论纷纷。"),
        DagNode(node_id="n_xumu", title="徙木立信",
                narrative="新法将颁，民众疑而不从。你于南门立三丈之木，重赏徙之者，以示令出必行。"),
        DagNode(node_id="n_jingtian", title="废井开阡陌",
                narrative="你欲废井田、开阡陌，许土地买卖。庶民欢腾，宗室哗然。"),
        DagNode(node_id="n_xianzhi", title="行县制 · 集权于君",
                narrative="你设三十一县，置令丞，以代世卿。郡县长吏由君任免，旧贵手中权柄大削。"),
        DagNode(node_id="n_taizi", title="太子犯禁",
                narrative="新法初行，太子驷犯之。法之不行，自上犯之——你欲依法处置，朝中惊骇。"),
        DagNode(node_id="n_compromise", title="姑息一时",
                narrative="你接受公子虔等人的劝退，对太子未予追究。新法权威自此动摇。",
                is_terminal=True),
        DagNode(node_id="n_punish", title="刑其师傅",
                narrative="你劓公子虔，黥公孙贾，以示太子之罪坐其师。新法立威，旧贵恨极。"),
        DagNode(node_id="n_strong_qin", title="国富兵强",
                narrative="十数年间，秦民勇于公战，怯于私斗，府库充盈，东出已有底气。"),
        DagNode(node_id="n_after_xiao", title="孝公薨 · 旧贵反扑",
                narrative="孝公既薨，惠文君立。公子虔等告卫鞅谋反，你被车裂于彤——然新法因国之所赖，得以延续。",
                is_terminal=True),
    ],
    edges=[
        DagEdge(edge_id="e_inqin_xumu", from_node="n_in_qin", to_node="n_xumu",
                label="先立公信 · 徙木为约",
                effects=[Effect(var="trust", op="inc", value=1)],
                fallback_narrative="你深知新法须以信立。"),
        DagEdge(edge_id="e_xumu_jingtian", from_node="n_xumu", to_node="n_jingtian",
                label="废井田 · 开阡陌",
                effects=[Effect(var="opposition", op="inc", value=2),
                         Effect(var="strength", op="inc", value=1)],
                fallback_narrative="动旧制者，旧贵必怒。"),
        DagEdge(edge_id="e_xumu_xianzhi", from_node="n_xumu", to_node="n_xianzhi",
                label="行县制 · 削宗室",
                effects=[Effect(var="opposition", op="inc", value=2),
                         Effect(var="trust", op="inc", value=1)],
                fallback_narrative="集权于君，孝公益信。"),
        DagEdge(edge_id="e_jingtian_taizi", from_node="n_jingtian", to_node="n_taizi",
                label="新法初行 · 太子犯禁",
                effects=[],
                fallback_narrative="法令一施，朝堂亦在试探。"),
        DagEdge(edge_id="e_xianzhi_taizi", from_node="n_xianzhi", to_node="n_taizi",
                label="集权之锋 · 直触太子",
                effects=[],
                fallback_narrative="新法所到，无人例外。"),
        DagEdge(edge_id="e_taizi_compromise", from_node="n_taizi", to_node="n_compromise",
                label="姑息从权 · 法威自损",
                conditions=[Condition(var="trust", op="lt", value=5)],
                effects=[Effect(var="strength", op="dec", value=2),
                         Effect(var="opposition", op="inc", value=1)],
                fallback_narrative="孝公犹豫，你只得退让。"),
        DagEdge(edge_id="e_taizi_punish", from_node="n_taizi", to_node="n_punish",
                label="刑其师傅 · 法威立",
                conditions=[Condition(var="trust", op="ge", value=5)],
                effects=[Effect(var="opposition", op="inc", value=2),
                         Effect(var="law_kept", op="set", value=1)],
                fallback_narrative="非常之时，行非常之法。"),
        DagEdge(edge_id="e_punish_strong", from_node="n_punish", to_node="n_strong_qin",
                label="耕战行十年 · 国势日隆",
                effects=[Effect(var="strength", op="inc", value=3),
                         Effect(var="trust", op="inc", value=1)],
                fallback_narrative="令出必行，国力大长。"),
        DagEdge(edge_id="e_strong_after", from_node="n_strong_qin", to_node="n_after_xiao",
                label="孝公薨后 · 旧贵反扑",
                conditions=[Condition(var="law_kept", op="eq", value=1),
                            Condition(var="opposition", op="ge", value=5)],
                effects=[],
                fallback_narrative="法虽存，身已不能保。"),
    ],
)


_wang_anshi = Scenario(
    scenario_id="song-wang-anshi-bianfa",
    title="王安石变法（熙宁新法）",
    period="北宋 · 宋神宗熙宁年间 · 公元 1069 ~ 1085 年",
    summary="神宗欲富国强兵，召王安石入相，行青苗、均输、免役、市易诸法。司马光等元老群起反对，新党旧党水火不容，新法在反复废立中走向尾声。",
    state_vars=[
        StateVar(key="emperor_will", label="神宗决心", kind=StateVarKind.SCALE, bits=3, initial=5,
                 description="0~7，初始 5"),
        StateVar(key="conservative", label="旧党反对", kind=StateVarKind.SCALE, bits=3, initial=4,
                 description="0~7，初始 4"),
        StateVar(key="finance", label="国库充盈", kind=StateVarKind.SCALE, bits=3, initial=2,
                 description="0~7，初始 2"),
        StateVar(key="people", label="民间评价", kind=StateVarKind.SCALE, bits=3, initial=4,
                 description="0~7，初始 4"),
    ],
    start_node="n_ru_xiang",
    nodes=[
        DagNode(node_id="n_ru_xiang", title="熙宁入相",
                narrative="神宗召你入相，问以富国之策。你以《本朝百年无事札子》对之，主张「理财为方今先急」。"),
        DagNode(node_id="n_qing_miao", title="行青苗法",
                narrative="春贷青苗钱于农户，秋收加息归还。本欲除豪强兼并，地方却强配派额，民怨初起。"),
        DagNode(node_id="n_jun_shu", title="行均输 · 市易",
                narrative="令发运使均输诸路赋税，置市易务平抑物价。商贾受抑，士林哗然。"),
        DagNode(node_id="n_mian_yi", title="行免役法",
                narrative="改差役为雇役，按户等纳免役钱。穷户骤添现钱之苦，富户却得脱繁役。"),
        DagNode(node_id="n_si_ma", title="司马光上书",
                narrative="司马光、苏轼、文彦博相继上书力谏，称新法扰民。你需向神宗陈情，争一时去留。"),
        DagNode(node_id="n_compromise", title="罢免新党",
                narrative="神宗动摇，外放王安石，召司马光还朝。新法名存实亡。",
                is_terminal=True),
        DagNode(node_id="n_continue", title="天下方田",
                narrative="你坚定推进，置提举常平官行方田均税法。府库渐充，禁军可练，西北边事稍振。"),
        DagNode(node_id="n_drought", title="熙宁旱灾 · 流民图",
                narrative="郑侠绘《流民图》上呈神宗，太皇太后流泪劝谏。神宗心摇，新法面临最严风暴。"),
        DagNode(node_id="n_recover", title="新法暂续",
                narrative="你二度入相，整顿吏治、严督执行，新法虽损而未废，西北开熙河，国库岁入倍增。"),
        DagNode(node_id="n_final", title="元祐更化",
                narrative="神宗崩，哲宗幼立，太皇太后听政，司马光尽罢新法，史称「元祐更化」。",
                is_terminal=True),
    ],
    edges=[
        DagEdge(edge_id="e_ru_qing", from_node="n_ru_xiang", to_node="n_qing_miao",
                label="先除兼并 · 行青苗法",
                effects=[Effect(var="conservative", op="inc", value=1),
                         Effect(var="people", op="dec", value=1)],
                fallback_narrative="你欲先松民困，却启争议之端。"),
        DagEdge(edge_id="e_qing_jun", from_node="n_qing_miao", to_node="n_jun_shu",
                label="续行均输 · 市易",
                effects=[Effect(var="conservative", op="inc", value=1),
                         Effect(var="finance", op="inc", value=1)],
                fallback_narrative="国库初见涟漪，士林波澜大作。"),
        DagEdge(edge_id="e_qing_mian", from_node="n_qing_miao", to_node="n_mian_yi",
                label="续行免役 · 雇役制",
                effects=[Effect(var="conservative", op="inc", value=2),
                         Effect(var="finance", op="inc", value=1),
                         Effect(var="people", op="dec", value=1)],
                fallback_narrative="差雇之变，触动最广人户。"),
        DagEdge(edge_id="e_jun_si", from_node="n_jun_shu", to_node="n_si_ma",
                label="士林哗然 · 司马光上书",
                effects=[],
                fallback_narrative="旧党联书，朝议沸腾。"),
        DagEdge(edge_id="e_mian_si", from_node="n_mian_yi", to_node="n_si_ma",
                label="差雇激变 · 旧党合力",
                effects=[],
                fallback_narrative="新法虽利国，民怨却未除。"),
        DagEdge(edge_id="e_si_compromise", from_node="n_si_ma", to_node="n_compromise",
                label="退让从公议 · 自请外放",
                conditions=[Condition(var="emperor_will", op="lt", value=5)],
                effects=[Effect(var="emperor_will", op="dec", value=2)],
                fallback_narrative="神宗既疑，去意亦坚。"),
        DagEdge(edge_id="e_si_continue", from_node="n_si_ma", to_node="n_continue",
                label="据理力争 · 行方田均税",
                conditions=[Condition(var="emperor_will", op="ge", value=5)],
                effects=[Effect(var="finance", op="inc", value=2),
                         Effect(var="conservative", op="inc", value=1)],
                fallback_narrative="神宗信你，新法续行。"),
        DagEdge(edge_id="e_continue_drought", from_node="n_continue", to_node="n_drought",
                label="熙宁大旱 · 流民图至",
                effects=[Effect(var="people", op="dec", value=2),
                         Effect(var="emperor_will", op="dec", value=1)],
                fallback_narrative="天灾骤至，舆论再翻。"),
        DagEdge(edge_id="e_drought_recover", from_node="n_drought", to_node="n_recover",
                label="二度入相 · 整顿吏治",
                conditions=[Condition(var="finance", op="ge", value=4)],
                effects=[Effect(var="finance", op="inc", value=1),
                         Effect(var="people", op="inc", value=1)],
                fallback_narrative="财已稍丰，犹可再图。"),
        DagEdge(edge_id="e_drought_final", from_node="n_drought", to_node="n_final",
                label="无力回天 · 神宗忧崩",
                conditions=[Condition(var="finance", op="lt", value=4)],
                effects=[],
                fallback_narrative="财不继、民亦疲，新法终废。"),
        DagEdge(edge_id="e_recover_final", from_node="n_recover", to_node="n_final",
                label="神宗崩 · 元祐更化",
                effects=[],
                fallback_narrative="人亡政息，史册留叹。"),
    ],
)


_REGISTRY[_shang_yang.scenario_id] = _shang_yang
_REGISTRY[_wang_anshi.scenario_id] = _wang_anshi


_yangwu = Scenario(
    scenario_id="qing-yangwu-yundong",
    title="洋务运动",
    period="晚清 · 同治至光绪初年 · 1861 ~ 1895 年",
    summary="两次鸦片战败，朝廷自强求富。曾国藩、李鸿章、左宗棠各执一端：是先海防造舰，还是先塞防西征？是官办独大，还是引商入局？甲午一炮，三十年血本散于黄海。",
    state_vars=[
        StateVar(key="industry", label="实业根基", kind=StateVarKind.SCALE, bits=3, initial=1,
                 description="0~7，0 为无近代厂矿，7 为体系初成"),
        StateVar(key="navy", label="海军实力", kind=StateVarKind.SCALE, bits=3, initial=0,
                 description="0~7，0 为旧式水师，7 为亚洲一流"),
        StateVar(key="frontier", label="塞防边疆", kind=StateVarKind.SCALE, bits=3, initial=2,
                 description="0~7，新疆 / 西北稳固度"),
        StateVar(key="conservatives", label="守旧阻力", kind=StateVarKind.SCALE, bits=3, initial=4,
                 description="0~7，朝中清流与顽固派的合力"),
        StateVar(key="merchant", label="商力引入", kind=StateVarKind.BOOL, bits=1, initial=0,
                 description="是否启用『官督商办』模式"),
    ],
    start_node="n_zongli",
    nodes=[
        DagNode(node_id="n_zongli", title="设总理衙门",
                narrative="咸丰新崩，恭亲王奕䜣力主仿西法设总理各国事务衙门，统筹外交与新政。曾国藩、李鸿章、左宗棠俱以军功膺疆寄。"),
        DagNode(node_id="n_arsenal", title="江南制造总局",
                narrative="曾国藩在上海高昌庙圈地，李鸿章续办，江南制造总局成中国近代第一大军工厂，造船造炮，亦译西书。"),
        DagNode(node_id="n_fuzhou", title="福州船政局",
                narrative="左宗棠在福州马尾设船政局，沈葆桢继任，造船与办学并重，开船政学堂育海军人才。"),
        DagNode(node_id="n_haifang_saifang", title="海防塞防之争",
                narrative="日本侵台、阿古柏据疆，国库不继。李鸿章主缓塞防而专海防，左宗棠拍案：『重新疆者所以保蒙古，保蒙古者所以卫京师』。"),
        DagNode(node_id="n_xizheng", title="左公西征",
                narrative="左宗棠抬棺出关，胡雪岩借洋债以济军饷，三年平定阿古柏，伊犁返还。新疆建省。",
                is_terminal=False),
        DagNode(node_id="n_beiyang", title="北洋水师成军",
                narrative="李鸿章督办北洋，购定远、镇远铁甲于德意志，建威海卫军港，开旅顺船坞。1888 年成军，号称亚洲第一。",
                is_terminal=False),
        DagNode(node_id="n_guandu_shangban", title="官督商办",
                narrative="盛宣怀办轮船招商局、电报总局、汉阳铁厂，引商股以济官力。利权稍归华人，但官商缠斗不绝。"),
        DagNode(node_id="n_jiawu", title="甲午之殇",
                narrative="日本明治维新二十年，海军跃进。北洋舰队炮弹掺沙、煤劣航迟，黄海一战折戟，威海卫陷。马关条约割台赔银，三十年自强一朝散尽。",
                is_terminal=True),
        DagNode(node_id="n_wuxu_eve", title="维新前夜",
                narrative="洋务三十年，器物虽具而制度未变。康梁登场，公车上书，光绪召见，变法之议汹涌于朝堂——洋务一代功业，终成戊戌之先声。",
                is_terminal=True),
        DagNode(node_id="n_collapse", title="顽固反扑",
                narrative="倭仁、徐桐之徒抗疏：『立国之道，尚礼义不尚权谋』。同文馆停招正途，制造局裁撤过半，新政气脉中断。",
                is_terminal=True),
    ],
    edges=[
        DagEdge(edge_id="e_zongli_arsenal", from_node="n_zongli", to_node="n_arsenal",
                label="先办军工 · 师夷长技",
                effects=[Effect(var="industry", op="inc", value=2),
                         Effect(var="conservatives", op="inc", value=1)],
                fallback_narrative="你支持曾李，先以军工立基。"),
        DagEdge(edge_id="e_zongli_fuzhou", from_node="n_zongli", to_node="n_fuzhou",
                label="海上立国 · 先办船政",
                effects=[Effect(var="navy", op="inc", value=1),
                         Effect(var="industry", op="inc", value=1)],
                fallback_narrative="你倾向左公之议，先建船政。"),
        DagEdge(edge_id="e_zongli_collapse", from_node="n_zongli", to_node="n_collapse",
                label="守祖宗之法 · 罢议新政",
                conditions=[Condition(var="conservatives", op="ge", value=4)],
                effects=[Effect(var="conservatives", op="set", value=7)],
                fallback_narrative="你向清流低头，新政胎死腹中。"),

        DagEdge(edge_id="e_arsenal_debate", from_node="n_arsenal", to_node="n_haifang_saifang",
                label="军工初备 · 议海防塞防",
                effects=[Effect(var="industry", op="inc", value=1)],
                fallback_narrative="军工渐立，国策之争浮上朝堂。"),
        DagEdge(edge_id="e_fuzhou_debate", from_node="n_fuzhou", to_node="n_haifang_saifang",
                label="船政成绪 · 议海防塞防",
                effects=[Effect(var="navy", op="inc", value=1)],
                fallback_narrative="船政有成，仍须抉择西北东南孰先。"),

        DagEdge(edge_id="e_debate_xizheng", from_node="n_haifang_saifang", to_node="n_xizheng",
                label="塞防为先 · 左公出关",
                effects=[Effect(var="frontier", op="set", value=7),
                         Effect(var="navy", op="dec", value=1)],
                fallback_narrative="你支持塞防，左公抬棺西行。"),
        DagEdge(edge_id="e_debate_beiyang", from_node="n_haifang_saifang", to_node="n_beiyang",
                label="海防为重 · 购舰建港",
                effects=[Effect(var="navy", op="set", value=6),
                         Effect(var="frontier", op="dec", value=1)],
                fallback_narrative="你支持海防，定远镇远启程。"),

        DagEdge(edge_id="e_xizheng_merchant", from_node="n_xizheng", to_node="n_guandu_shangban",
                label="军费殷需 · 引商入局",
                effects=[Effect(var="merchant", op="set", value=1),
                         Effect(var="industry", op="inc", value=2)],
                fallback_narrative="胡雪岩之后，盛宣怀续开商办之路。"),
        DagEdge(edge_id="e_beiyang_merchant", from_node="n_beiyang", to_node="n_guandu_shangban",
                label="海军耗银 · 招商济饷",
                effects=[Effect(var="merchant", op="set", value=1),
                         Effect(var="industry", op="inc", value=1)],
                fallback_narrative="北洋经费不足，转向官督商办。"),

        DagEdge(edge_id="e_beiyang_jiawu", from_node="n_beiyang", to_node="n_jiawu",
                label="挪款修园 · 黄海折戟",
                conditions=[Condition(var="merchant", op="eq", value=0)],
                effects=[Effect(var="navy", op="set", value=2)],
                fallback_narrative="军费被挪，舰队疲敝，甲午一战终败。"),

        DagEdge(edge_id="e_merchant_eve", from_node="n_guandu_shangban", to_node="n_wuxu_eve",
                label="器物已成 · 制度待变",
                conditions=[Condition(var="merchant", op="eq", value=1),
                            Condition(var="industry", op="ge", value=4)],
                effects=[],
                fallback_narrative="洋务三十年功业，铸成戊戌变法之先声。"),
        DagEdge(edge_id="e_merchant_jiawu", from_node="n_guandu_shangban", to_node="n_jiawu",
                label="海军未振 · 仍蹈覆辙",
                conditions=[Condition(var="navy", op="lt", value=4)],
                effects=[],
                fallback_narrative="海军根基不稳，甲午终成定局。"),
    ],
)


_REGISTRY[_yangwu.scenario_id] = _yangwu


def list_scenarios() -> list[Scenario]:
    return list(_REGISTRY.values())


def get_scenario(scenario_id: str) -> Scenario | None:
    return _REGISTRY.get(scenario_id)


def register_scenario(scenario: Scenario) -> None:
    _REGISTRY[scenario.scenario_id] = scenario

